language: node_js
node_js:
  - "9.11.1"
sudo: required
services: 
  - docker

before_install:
  - docker build -t yrios056/docker-react -f Dockerfile.dev .

script:
  - docker run yrios056/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-794787537676"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"